spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/minipia
    username: root
    password: be2107fg!

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    baseline-version: 0
    out-of-order: true
    clean-disabled: true
